-- Script SQL para criar a tabela de imóveis e configurar as permissões no Supabase.
-- Execute este script no editor SQL (SQL Editor) do seu painel do Supabase.

-- 1. Criar a tabela 'properties'
CREATE TABLE IF NOT EXISTS public.properties (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text,
    price numeric NOT NULL,
    area numeric NOT NULL,
    type text NOT NULL,
    transaction_type text NOT NULL,
    location text NOT NULL,
    lat double precision NOT NULL,
    lng double precision NOT NULL,
    images text[] DEFAULT '{}'::text[],
    is_verified boolean DEFAULT true,
    is_featured boolean DEFAULT false,
    bedrooms integer,
    bathrooms integer,
    agent jsonb NOT NULL DEFAULT '{"name": "Idelcilio Vieira", "phone": "(88) 99269-4661", "email": "contato@idelciliovieira.com", "avatar": "https://i.postimg.cc/RhQSsxHQ/logo-idelcilio.jpg"}'::jsonb,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    views integer DEFAULT 0 NOT NULL,
    status text DEFAULT 'active'::text NOT NULL
);

-- Habilitar Row Level Security (RLS) para segurança
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;

-- 2. Criar políticas de acesso (Policies)
-- Permitir que qualquer pessoa leia os anúncios
DROP POLICY IF EXISTS "Permitir leitura pública de anúncios" ON public.properties;
CREATE POLICY "Permitir leitura pública de anúncios" 
ON public.properties FOR SELECT 
USING (true);

-- Permitir qualquer operação (Inserir, Atualizar, Deletar) para usuários autenticados ou por simplicidade de entrega via chave anon
DROP POLICY IF EXISTS "Permitir modificações públicas temporárias" ON public.properties;
CREATE POLICY "Permitir modificações públicas temporárias" 
ON public.properties FOR ALL 
USING (true)
WITH CHECK (true);

-- Nota: Para habilitar o upload de arquivos no Storage, lembre-se de:
-- 1. Ir em 'Storage' no painel lateral esquerdo do Supabase.
-- 2. Clicar em 'New bucket' e criar um bucket chamado: property-images
-- 3. Marcar a opção 'Public bucket' para permitir que as imagens sejam vistas publicamente.
-- 4. Nas configurações do bucket, adicione uma política permitindo 'Allowed operations': INSERT e SELECT para todos (anon).

-- -----------------------------------------------------------------------------
-- 3. Criar a tabela 'portfolio_projects' (Portfólio de Obras e Engenharia)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portfolio_projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    category text NOT NULL,
    location text,
    description text,
    image text NOT NULL,
    gallery text[] DEFAULT '{}'::text[],
    year text,
    area text,
    status text DEFAULT 'Concluído'::text NOT NULL,
    features text[] DEFAULT '{}'::text[],
    instagram_url text,
    before_image text,
    after_image text,
    responsible_name text DEFAULT 'Eng. Idelcilio Vieira (CREA 356611CE)'::text,
    is_featured boolean DEFAULT false,
    active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar Row Level Security (RLS) para o portfólio
ALTER TABLE public.portfolio_projects ENABLE ROW LEVEL SECURITY;

-- Permitir leitura pública dos projetos do portfólio
DROP POLICY IF EXISTS "Permitir leitura pública de projetos do portfolio" ON public.portfolio_projects;
CREATE POLICY "Permitir leitura pública de projetos do portfolio" 
ON public.portfolio_projects FOR SELECT 
USING (true);

-- Permitir modificações para o painel admin
DROP POLICY IF EXISTS "Permitir modificações públicas no portfolio" ON public.portfolio_projects;
CREATE POLICY "Permitir modificações públicas no portfolio" 
ON public.portfolio_projects FOR ALL 
USING (true)
WITH CHECK (true);
